### ISSUE TITLE
Date is incorrect on Pi

### ISSUE THREAD

**Issue by arandell93** [LakeMaps/boat#145]
The Pi thinks every day is 2017-04-10, thus all log files appear to have been made then, despite the log files being named incorrectly per #144.

@FifoIronton has a screen shot for details.

**Comment by arandell93** [comment]
Idea: Can we get it to pull real-world from either:

1. The shoreside (or any) computer once the network is up (ideal)
2. The GPS once the satellites get signal (not-ideal)

**Comment by whymarrh** [comment]
The GPS would be ideal IMO, as that's the most accurate time source (atomic clocks and whatnot). We can certainly pull from the shoreside by default and use the GPS to adjust once we have signal.

**Comment by arandell93** [comment]
Yeah let's do that. At least then we will always have a system time regardless of GPS state, but can use GPS for real pretty accuracy once we get it.
