### ISSUE TITLE
Investigate Potential Sources of Latency

### ISSUE THREAD

**Issue by arandell93** [LakeMaps/boat#17]
More testing is required to determine the sources of latency within the controller input - motor output chain.

It would be beneficial to quantify the latency as best as possible, then vary individual parts of the control system to determine the affect they have on overall system latency.

Brainstorm possible sources here and we can determine the most likely sources in order to address those first.

**Comment by arandell93** [comment]
I will investigate and quantify the time elapsed between sending a speed value to the Propulsion Module. (Ref [microcontrollers/issues/6](https://github.com/LakeMaps/microcontrollers/issues/6))

**Comment by whymarrh** [comment]
I'm closing this seeing how LakeMaps/microcontrollers#6 and LakeMaps/microcontrollers#7 are closed.
