### ISSUE TITLE
Error constructing dynamic protobuf messages

### ISSUE THREAD

**Issue by whymarrh** [LakeMaps/boat#32]
When constructing dynamic protobuf message schemas, the byte array passed to [`FileDescriptorSet#parseFrom(byte[])`](https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/DescriptorProtos.FileDescriptorSet.html#parseFrom-byte:A-) causes an [`InvalidProtocolBufferException`](https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/InvalidProtocolBufferException) to be thrown.

**Comment by whymarrh** [comment]
I'll try to take a look at this tomorrow—it will be a blocker for our next bench test.

**Comment by whymarrh** [comment]
I will hopefully take a look at his before Tuesday.

**Comment by arandell93** [comment]
When you said a blocker for our next bench test, did you mean to finish troubleshooting 1.0.1 or did you mean to move past that?

**Comment by whymarrh** [comment]
Rev 1.0.1, yeah.

**Comment by whymarrh** [comment]
🎉 🎉 🎉 🎉 Woo! Only 6 days off on my time estimate! 🎉 🎉 🎉 🎉
