### ISSUE TITLE
Develop 'Loopback' Functionality

### ISSUE THREAD

**Issue by arandell93** [LakeMaps/boat#51]
Refs #47  and Lakemaps/Hangashore#32

In order to quantify the system latency, the boat needs to re-transmit any messages it receives from the wireless link. 

The shoreside will be used to timestamp when it sends a message and again when it receives the same message back over the link.

**Comment by arandell93** [comment]
This will be completed and tested tonight as part of #47.

**Comment by whymarrh** [comment]
As per the last comments in #47, we're not tackling this right now.
