### ISSUE TITLE
Convert position information from GPS into DMS

### ISSUE THREAD

**Issue by whymarrh** [LakeMaps/boat#53]
`GGA` and `RMC` offer latitude and longitude in `ddmm.mmmm`. These should be converted into [DMS](https://en.wikipedia.org/wiki/Decimal_degrees).

From pp. 19 and 22 from the [FGPMMOPA6H datasheet](https://cdn-shop.adafruit.com/datasheets/GlobalTop-FGPMMOPA6H-Datasheet-V0A.pdf):

| Name | Example | Description |
|:---|:---|:---|
| Latitude | 2307.1256 | ddmm.mmmm |
| Longitude | 12016.4438 | dddmm.mmmm |

**Comment by arandell93** [comment]
> These should be converted into DMS.

You state Degrees, Minutes, Seconds but link to decimal degrees. I assume you had intended to use decimal degrees? (As it is the superior unit)

**Comment by whymarrh** [comment]
¯\\\_(ツ)\_/¯

**Comment by arandell93** [comment]
Use decimal degrees.

**Comment by whymarrh** [comment]
This was added in 604710d725bc1275defb117895121dfba989f0d9 but will certainly need to "cleaned up" at some point
