### ISSUE TITLE
Update Block Diagram on Wiki

### ISSUE THREAD

**Issue by arandell93** [LakeMaps/boat#60]
Block diagrams need to be updated/added to the wiki for:

- [x] Rev 1.0.1

- [x] Rev 1.2 

- [x] Rev 1.3

**Comment by arandell93** [comment]
Rev 1.0.1
![block diagram 1 0 1 2017-03-25](https://cloud.githubusercontent.com/assets/10678515/24324224/5c52871a-1165-11e7-9f99-f81e1ba522a7.png)

**Comment by arandell93** [comment]
Rev 1.2:
![block diagram 1 2 2017-03-25](https://cloud.githubusercontent.com/assets/10678515/24324237/bf6bbc18-1165-11e7-9f42-b0e4c1edb6ad.png)

**Comment by arandell93** [comment]
Rev 1.3:
![block diagram 1 3 2017-03-25](https://cloud.githubusercontent.com/assets/10678515/24324338/adba0644-1167-11e7-91f6-aab650fe6cc4.png)

**Comment by whymarrh** [comment]
@arandell93 please update the tasks in the OP and close this once this is done.
