### ISSUE TITLE
Implement hardware serial GPS

### ISSUE THREAD

**Issue by whymarrh** [LakeMaps/boat#90]
Refs #40

We will need to add a new GPS with a higher update rate.

**Comment by whymarrh** [comment]
@arandell93 would you mind linking the data sheet for the new GPS?

**Comment by arandell93** [comment]
[Datasheet](https://cdn-shop.adafruit.com/datasheets/GlobalTop-FGPMMOPA6H-Datasheet-V0A.pdf)

**Comment by arandell93** [comment]
For my own reference. We will need to use PI GPIO pins 4, 6, 8, 10 which are +5, GND, TX and RX respectively.
![image](https://cloud.githubusercontent.com/assets/10678515/26676742/9ea486ea-46a3-11e7-9ed8-15b6a077d0b5.png)

**Comment by whymarrh** [comment]
Just to confirm that I'm not missing something here—we're simply switching between using the passthrough microcontroller to connecting the same GPS directly to the Pi, yeah? (I'm not sure why I previously referred to a "new" GPS.)

**Comment by whymarrh** [comment]
As for the battery backup (from the link):

> Normally, if the GPS loses power, it will revert to the factory default for baud rates, configuration, etc. A backup battery will mean that those defaults will not be lost!
>
> The backup real-time-clock circuitry draws 7 uA (0.007 mA) so a CR1220 will last 40mAh / 0.007mA = 5,714 hours = 240 days continuously. The backup battery is only used when there's no main 3V power to the GPS, so as long as it's only used as backup once in a while, it will last years

No thanks—we will need to add the ability to configure the GPS at startup anyway so we may as well always *need* do it.

**Comment by arandell93** [comment]
> we're simply switching between using the passthrough microcontroller to connecting the same GPS directly to the Pi, yeah? (I'm not sure why I previously referred to a "new" GPS.)

It is functionally the same, but we are in fact going from using the old GPS to using the new ones we recently bought. That's why we need to do the settings.

> No thanks—we will need to add the ability to configure the GPS at startup anyway (for when the battery inevitably dies) so we may as well always need do it.

I am okay with this.

**Comment by whymarrh** [comment]
> It is functionally the same, but we are in fact going from using the old GPS to using the new ones we recently bought. That's why we need to do the settings.

That would make sense. It would also explain why I previously referred to a "new" GPS. The confusion stemmed from the fact that the linked datasheet is the same datasheet I wrote the current GPS implementation against (which is a good thing I guess). Anyhow, it all makes sense now.

**Comment by arandell93** [comment]
_
           /(|
          (  :
         __\  \  _____
       (____)  `|
      (____)|   |
       (____).__|
        (___)__.|_____
